services:
  postgres:
    container_name: postgres-sql-book-verse
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_verse
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - book-verse-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-book-verse
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - book-verse-network
  keycloak:
    container_name: keycloak-book-verse
    image: quay.io/keycloak/keycloak:25.0.4
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - "start-dev"
    networks:
      - book-verse-network
networks:
  book-verse-network:
    driver: bridge

volumes:
  postgres:
    driver: local